# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 04:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('armor_name', models.CharField(blank=True, max_length=30)),
                ('ac_bonus', models.SmallIntegerField(blank=True, null=True)),
                ('max_dex', models.SmallIntegerField(blank=True, null=True)),
                ('armor_penalty', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_name', models.CharField(max_length=30)),
                ('atk_bonus', models.SmallIntegerField(blank=True, null=True)),
                ('crit', models.CharField(blank=True, max_length=30)),
                ('damage', models.CharField(blank=True, max_length=30)),
                ('range', models.SmallIntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('race', models.CharField(max_length=30)),
                ('char_class', models.CharField(max_length=30)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feat_name', models.CharField(blank=True, max_length=30)),
                ('feat_desc', models.TextField(blank=True)),
                ('belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charsheet.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=30)),
                ('item_weight', models.SmallIntegerField(blank=True, null=True)),
                ('belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charsheet.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(blank=True, max_length=100)),
                ('link_url', models.URLField(blank=True)),
                ('belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charsheet.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Maneuvers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmb', models.SmallIntegerField(blank=True, null=True)),
                ('cmd', models.SmallIntegerField(blank=True, null=True)),
                ('belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charsheet.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Misc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.SmallIntegerField(blank=True, null=True)),
                ('ac', models.SmallIntegerField(blank=True, null=True)),
                ('flatfooted_ac', models.SmallIntegerField(blank=True, null=True)),
                ('touch_ac', models.SmallIntegerField(blank=True, null=True)),
                ('init', models.SmallIntegerField(blank=True, null=True)),
                ('speed', models.SmallIntegerField(blank=True, null=True)),
                ('damage_resistance', models.SmallIntegerField(blank=True, null=True)),
                ('languages', models.TextField(blank=True)),
                ('belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charsheet.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold', models.SmallIntegerField(blank=True, null=True)),
                ('silver', models.SmallIntegerField(blank=True, null=True)),
                ('copper', models.SmallIntegerField(blank=True, null=True)),
                ('belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charsheet.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Saves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fort', models.SmallIntegerField(blank=True, null=True)),
                ('reflex', models.SmallIntegerField(blank=True, null=True)),
                ('will', models.SmallIntegerField(blank=True, null=True)),
                ('belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charsheet.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=30)),
                ('ranks', models.SmallIntegerField(blank=True, null=True)),
                ('belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charsheet.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Spells',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spell_name', models.CharField(blank=True, max_length=100)),
                ('spell_desc', models.TextField(blank=True)),
                ('spell_lvl', models.SmallIntegerField(blank=True, null=True)),
                ('belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charsheet.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str', models.SmallIntegerField(blank=True, null=True)),
                ('dex', models.SmallIntegerField(blank=True, null=True)),
                ('con', models.SmallIntegerField(blank=True, null=True)),
                ('int', models.SmallIntegerField(blank=True, null=True)),
                ('wis', models.SmallIntegerField(blank=True, null=True)),
                ('cha', models.SmallIntegerField(blank=True, null=True)),
                ('belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charsheet.Character')),
            ],
        ),
        migrations.AddField(
            model_name='attacks',
            name='belongs_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charsheet.Character'),
        ),
        migrations.AddField(
            model_name='armor',
            name='belongs_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charsheet.Character'),
        ),
    ]
