# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-29 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armor',
            name='armor_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='attacks',
            name='attack_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='attacks',
            name='crit',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='attacks',
            name='damage',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='attacks',
            name='type',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='feats',
            name='feat_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feats',
            name='feat_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='gear',
            name='item_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='links',
            name='link_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='links',
            name='link_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skills',
            name='skill_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='spells',
            name='spell_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spells',
            name='spell_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
